name: Shell Commands 

on: push

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 
